server:
  port: 8003
spring:
  security:
    oauth2:

  redis:
    database: 0
    port: 6379
    host: localhost
    password:

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
