spring:
  datasource:
    name: base-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xadmin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

  hikari:
    pool-name: hikari-pool-
    minimum-idle: 4
    maximum-pool-size: 8
    connection-timeout: 30000
    connection-test-query: SELECT 1

  thymleaf:
    cache: false

  devtools:
    restart:
      enabled: true

file:
  upload:
    path: /tmp/upload