#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xadmin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 4
      maximum-pool-size: 8
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  codec:
    log-request-details: true

  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
      shutdown:
        await-termination: true
        await-termination-period: 10s
      thread-name-prefix: x-pool-
    scheduling:
      pool:
        size: 2
      shutdown:
        await-termination: true
        await-termination-period: 10s
      thread-name-prefix: x-task-

  cache:
    cache-names:
      - demo1
      - demo2
      - demo3
    redis:
      time-to-live: 100
    type: redis

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    database: ${REDIS_DB:0}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:Hjv@Y&*(O8JY&Y0T^&3J}
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

  devtools:
    restart:
      exclude: "static/**,public/**"

